version: '3.8'

services:
  timescale:
    image: timescale/timescaledb:latest-pg16
    container_name: air-timescale
    environment:
      POSTGRES_USER: air
      POSTGRES_PASSWORD: air
      POSTGRES_DB: energy
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U air -d energy"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    container_name: air-postgres
    environment:
      POSTGRES_USER: reporter
      POSTGRES_PASSWORD: reporter
      POSTGRES_DB: sales
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reporter -d sales"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: air-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ops
      MYSQL_USER: air
      MYSQL_PASSWORD: air
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "air", "-pair"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: air-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  air-py:
    build: ../dataserver
    container_name: air-py
    ports:
      - "9001:9001"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ../dataserver:/app
      - /tmp/air-py:/tmp/air-py

volumes:
  timescale_data:
  postgres_data:
  mysql_data:
  redis_data:
